# Generated by Django 4.2.16 on 2024-10-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Курснинг расмий номини киритинг (255 белгидан кўп эмас)', max_length=255, verbose_name='Курс номи')),
                ('description', models.TextField(help_text='Курс ҳақида тўлиқ маълумот беринг', verbose_name='Курс тавсифи')),
                ('is_modern', models.BooleanField(default=True, help_text='Курснинг замонавийлигини кўрсатинг', verbose_name='Замонавий курс')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курслар',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Часто задаваемый вопрос', max_length=255, verbose_name='Савол')),
                ('answer', models.TextField(help_text='Ответ на вопрос', verbose_name='Жавоб')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания вопроса', verbose_name='Яратилган вақти')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Янгиланган вақти')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Лиднинг исмини киритинг (100 та белгидан кўп эмас)', max_length=100, verbose_name='Исм')),
                ('last_name', models.CharField(help_text='Лиднинг фамилиясини киритинг (100 та белгидан кўп эмас)', max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(help_text='Лиднинг телефон рақамини киритинг (20 та белгидан кўп эмас)', max_length=20, verbose_name='Телефон рақами')),
                ('status', models.CharField(choices=[('pending', 'Жавоб бермаган'), ('confirmed', 'Келади'), ('declined', 'Келмайди')], default='pending', help_text="Лиднинг ҳолатини танланг: 'Жавоб бермаган', 'Келади' ёки 'Келмайди'", max_length=10, verbose_name='Ҳолат')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лидлар',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MentorStaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Менторнинг муайян йилдаги стажини киритинг', verbose_name='Йил')),
            ],
            options={
                'verbose_name': 'Ментор стажи',
                'verbose_name_plural': 'Ментор стажлари',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='StudentWorkProsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prosent', models.PositiveIntegerField(help_text='Битирувчиларнинг ишга жойлашганлик фоизини киритинг', verbose_name='Ишлаш фоизи')),
            ],
            options={
                'verbose_name': 'Битирувчилар иш фоизи',
                'verbose_name_plural': 'Битирувчилар иш фоизлари',
            },
        ),
    ]
