# Generated by Django 4.2.16 on 2024-10-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='is_modern',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Тавсиф сарлавҳасини киритинг', max_length=155, verbose_name='Тавсиф сарлавҳаси')),
                ('description', models.TextField(blank=True, help_text='Курс ҳақида тўлиқ маълумот киритинг', null=True, verbose_name='Тавсиф')),
                ('course', models.ForeignKey(help_text='Курсни танланг', on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Курс тавсифи',
                'verbose_name_plural': 'Курс тавсифлари',
                'ordering': ['title'],
            },
        ),
    ]
