# Generated by Django 4.2.16 on 2024-10-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_coursedescription_options_lead_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Лид', 'verbose_name_plural': 'Лидлар'},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'Жавоб бермаган'), ('confirmed', 'Келади'), ('declined', 'Келмайди'), ('no_call', 'Қўнғироқ қилинмади')], default='no_call', help_text="Лиднинг ҳолатини танланг: 'Жавоб бермаган', 'Келади' ёки 'Келмайди'", max_length=10, verbose_name='Ҳолат'),
        ),
    ]
