# Generated by Django 4.2.16 on 2024-10-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_lead_options_remove_lead_last_name_lead_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='marque_icon',
            field=models.CharField(default=0, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='marque_text',
            field=models.CharField(default=0, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='text',
            field=models.TextField(default=0, verbose_name='Курс ҳақида'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'Жавоб бермаган'), ('confirmed', 'Келади'), ('declined', 'Келмайди'), ('no_call', 'Қўнғироқ қилинмади')], default='no_call', help_text='Лиднинг ҳолатини танланг', max_length=10, verbose_name='Ҳолат'),
        ),
        migrations.CreateModel(
            name='SpecialistCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='specialist_courses/')),
                ('course', models.ForeignKey(help_text='Курсни танланг', on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('course', models.ForeignKey(help_text='Курсни танланг', on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Часто задаваемый вопрос', max_length=255, verbose_name='Савол')),
                ('answer', models.TextField(help_text='Ответ на вопрос', verbose_name='Жавоб')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Курс Савол-Жавоб',
                'verbose_name_plural': 'Курс Савол-Жавоблари',
            },
        ),
    ]
