# Generated by Django 4.2.3 on 2024-10-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_marque_icon_course_marque_text_course_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursefaq',
            options={'verbose_name': 'Course FAQ', 'verbose_name_plural': 'Course FAQs'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'Frequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='mentorstaje',
            options={'ordering': ['year'], 'verbose_name': 'Mentor Experience', 'verbose_name_plural': 'Mentor Experiences'},
        ),
        migrations.AlterModelOptions(
            name='studentworkprosent',
            options={'verbose_name': 'Graduate Employment Percentage', 'verbose_name_plural': 'Graduate Employment Percentages'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='text',
        ),
        migrations.AddField(
            model_name='course',
            name='text_1',
            field=models.TextField(default=0, verbose_name='About the Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='text_2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Enter the official name of the course (no more than 255 characters)', max_length=255, verbose_name='Course Title'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='course',
            field=models.ForeignKey(help_text='Select a course', on_delete=django.db.models.deletion.CASCADE, related_name='coursedescription', to='main.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='description',
            field=models.TextField(blank=True, help_text='Enter complete information about the course', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='title',
            field=models.CharField(help_text='Enter the title of the description', max_length=155, verbose_name='Description Title'),
        ),
        migrations.AlterField(
            model_name='coursefaq',
            name='answer',
            field=models.TextField(help_text='Answer to the question', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='coursefaq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursefaq',
            name='question',
            field=models.CharField(help_text='Frequently Asked Question', max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='coursefor',
            name='course',
            field=models.ForeignKey(help_text='Select a course', on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='Answer to the question', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the question was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(help_text='Frequently Asked Question', max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of the last update', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(help_text='Select a course', on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(help_text="Enter the lead's first name (no more than 100 characters)", max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(help_text="Enter the lead's phone number (no more than 20 characters)", max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'No Response'), ('confirmed', 'Will Attend'), ('declined', 'Will Not Attend'), ('no_call', 'Not Called')], default='no_call', help_text="Select the lead's status", max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mentorstaje',
            name='year',
            field=models.PositiveIntegerField(help_text="Enter the mentor's experience for the specified year", verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='specialistcourse',
            name='course',
            field=models.ForeignKey(help_text='Select a course', on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='studentworkprosent',
            name='prosent',
            field=models.PositiveIntegerField(help_text='Enter the employment rate of graduates', verbose_name='Employment Percentage'),
        ),
    ]
