# Generated by Django 4.2.3 on 2024-10-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_options_alter_coursefaq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='month_period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
